#!/usr/bin/env sh
# replace ls with exa
# install exa with apt (20.10 and higher) or with 'cargo install exa'
alias ls='exa'
# some more ls aliases
alias ll='ls -lF -I "*~"'
alias lk='ls -lF'
alias la='ls -aF'
alias  l='ls -F -I "*~"'

#typo correction
alias sl='ls'
alias ci='vi'
alias :q='exit'

# programs
alias r='ranger'
alias v='vim'
alias vi='vim'
alias SS='sudo systemctl'
alias balias='vi ~/.dotfiles/shell/alias'
alias sbash='source ~/.bashrc'
alias szsh='source ~/.zshrc'
alias vimrc='vi ~/.dotfiles/vimrc'
alias bashrc='vi ~/.dotfiles/bashrc'
alias inputrc='vi ~/.dotfiles/inputrc'
alias profile='vi ~/.dotfiles/profile'
alias functions='vi ~/.dotfiles/shell/funtions'

#navigation
alias q='exit'
# alias open='xdg-open &'

#utilities
alias whatismyip="ip route get 8.8.8.8 | awk '{print \$NF; exit}'"
alias sshconfig='vi ~/.ssh/config'
alias pdfme='find . -name "*.ps" -o -name "*.eps" -exec epstopdf {} ";"'
alias thesis='zathura ~/Documents/Final_Revised_delivered.pdf &'

#openfortvpn not quite working
# alias vpn="screen -d -m -S vpn sudo openfortivpn -c ~/.dotfiles_local/config/fortivpn/config"
alias vpn="screen -d -m -S vpn sudo openfortivpn -c ~/.dotfiles_local/config/fortivpn/config"

#Works with zsh, might break bash
alias d='dirs -v | head -10'
# alias 1='cd -'
# alias 2='cd -2'
# alias 3='cd -3'
# alias 4='cd -4'
# alias 5='cd -5'
# alias 6='cd -6'
# alias 7='cd -7'
# alias 8='cd -8'
# alias 9='cd -9'

# alias open='xdg-open'



# suffix aliases
alias -s {xyz,yml,yaml,py,run,txt,md,tcl,data,inp}=vim
alias -s ods='background libreoffice --nologo --calc'
alias -s odt='background libreoffice --nologo --writer'
alias -s {mkv,avi,mp4,mp3}='background vlc'
alias -s {pdf,eps,ps}=zathura

# iron merge

# alias ironmerge='echo "lmp_merge -n 3 surface_up min/max z surface_down min/max z your_data min/maxz -o data.combined.out"'
# sshfs pibsa
alias pibsa='sshfs rfapostolo@SSVNormandy:/data1/14.pibsa-pam/ ~/14.pibsa-pam && cd ~/14.pibsa-pam'
