#!/usr/bin/env sh
# set locale
export LC_ALL="en_GB.UTF-8"
# programs
export EDITOR="vim"
export GUI_EDITOR="subl"
export READER="zathura"
export BROWSER="google-chrome"

# variables
export OMP_NUM_THREADS=$(grep -c processor /proc/cpuinfo)
# export CUPS_USER="rapostol"

# Python virtual environments
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export WORKON_HOME=$HOME/.dotfiles/python/venvs
export PROJECT_HOME=$HOME/code
#source /home/rfapostolo/.local/bin/virtualenvwrapper.sh
