#!/usr/bin/env sh
# background processes
background () { "$@" > /dev/null 2&>1 & }
# go back N directories
cdn () { for i in $(seq "$1") ; do cd .. ; done ; }
open () { xdg-open "$@" > /dev/null 2>&1 & }

# make directory and enter it
mkd () { mkdir -pv -- "$1" && cd -P -- "$1" ; }

# do sudo, or sudo the last command if no argument given
s () { 
    if [[ $# == 0 ]]; then
        sudo $(history -p '!!')
    else
        sudo "$@"
    fi
}
export s

# extract any kind of archive
extract () {
   if [ -f $1 ] ; then
       case $1 in
           *.tar.bz2)   tar xvjf $1    ;;
           *.tar.gz)    tar xvzf $1    ;;
           *.bz2)       bunzip2 $1     ;;
           *.rar)       unrar x $1       ;;
           *.gz)        gunzip $1      ;;
           *.tar)       tar xvf $1     ;;
           *.tbz2)      tar xvjf $1    ;;
           *.tgz)       tar xvzf $1    ;;
           *.zip)       unzip $1       ;;
           *.Z)         uncompress $1  ;;
           *.7z)        7z x $1        ;;
           *)           echo "don't know how to extract '$1'..." ;;
       esac
  else
     echo "'$1' is not a valid file!"
  fi
}
export extract

#Backup drive
backupdata () {
	echo "Would you like to delete files on the backup that are not on the original anymore?"
	read answer
	if [[ $answer = "Y" || $answer = "y" || $answer = "Yes" || $answer = "yes" ]]; then
		rsync -glotrucvW --progress --inplace --delete --info=progress2 /data1/* /media/rfapostolo/RuiApostoloPHD4TB/PhD/ | tee ~/backuplog/"$(date +"%F_%T").del.log"
	else
		rsync -glotrucvW --progress --inplace --info=progress2 /data1/* /media/rfapostolo/RuiApostoloPHD4TB/PhD/ | tee ~/backuplog/"$(date +"%F_%T").nodel.log"
	fi
}

export backupdata

compress () {
tar cvf - $1 | pv -s $(du -sb $1 | awk '{print $1}') | pigz --best > $1.tar.gz
}
export compress

prm () {
rm -rv $1 | pv -l -s $( du -a $1 | wc -l ) > /dev/null
}
export prm
